name: gregory
favicon: null
layout_spectrum: 0.9194007278420031
typography_spectrum: 0.5134942785371095
title: Greg Nemer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#373737'
    - '#81b8da'
    - '#061228'
    - '#638498'
    - '#e4e4e6'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
